### ISSUE TITLE
app working?

### ISSUE THREAD

**Issue by Jepzelf** [aleksey-saenko/MusicRecognizer#1]
Installed the Audile app, got a token.
It does not recognize anything, not even superhits by the Beatles.

The app listens for 3 seconds, then re-tries for 3 seconds.
Following the msg, no matches found.
Tried very famous songs.

My device
Samsung A52
Android 13

**Comment by Jepzelf** [comment]
By what source "listens" the app?
Just tried playing an mp3 app, and Spotify.

I see no reaction in Audile,  it still does nothing.

On October 26, 2023 5:08:45 PM GMT+02:00, Doc Sniper ***@***.***> wrote:
> I listened to one of the audio files that the app records. Doesn't sound like the "original" sound. that you wanted to record, everything was extremely distorted. So of course audd can't recognize anything because the audio recording seems to have problems.
> 
> Audile 1.0.0 (from F-Droid) on Android 13 (LOS 20).
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/aleksey-saenko/MusicRecognizer/issues/1#issuecomment-1781319359
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>
-- 
Jan Volkers
0611243237

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aleksey-saenko** [comment]
@Jepzelf
If you try to recognize a song without an internet connection, the app schedules recognition and you can listen to the quality of the recording on the queue screen.
On my several devices, the recording function works well without any distortion, but I have some ideas why it is not working on yours. I will drop a build here for you to test after a while.

**Comment by Jepzelf** [comment]
There is no queue screen in the app that I see.

Again, to what source listens the app?

To add, I do not like that you can listen to what I record.
While I can not.


On October 26, 2023 6:05:36 PM GMT+02:00, Aleksey Saenko ***@***.***> wrote:
> @Jepzelf
> If you try to recognize a song without an internet connection, the app schedules recognition and you can listen to the quality of the recording on the queue screen.
> On my several devices, the recording function works well without any distortion, but I have some ideas why it is not working on yours. I will drop a build here for you to test after a while.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/aleksey-saenko/MusicRecognizer/issues/1#issuecomment-1781419086
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
-- 
Jan Volkers
0611243237

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aleksey-saenko** [comment]
@DocSniper 
@Jepzelf 
Can you please test audio recording and recognition for this build?
Jepzelf, the token will not be saved between versions (the test build is not signed by f-droid), but you can try without it.
The queue screen is available via preferences. And no one, except the device user and the remote service, can listen to what the app is recording during the recognition session. Btw, you can disable saving the record at all by disable recognition fallback actions.
[app-release_debug.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13180188/app-release_debug.zip)

**Comment by Jepzelf** [comment]
The app now shows a fluctuating sound level, which does not go above 0,5 no matter the volume of the tv.

Same still, no matches found.
It saved one recording, loud noise only.

On October 26, 2023 6:39:55 PM GMT+02:00, Aleksey Saenko ***@***.***> wrote:
> @DocSniper 
> @Jepzelf 
> Can you please test audio recording and recognition for this build?
> Jepzelf, the token will not be saved between versions (the test build is not signed by f-droid), but you can try without it.
> The queue screen is available via preferences. And no one, except the device user and the remote service, can listen to what the app is recording during the recognition session. Btw, you can disable saving the record at all by disable recognition fallback actions.
> [app-release_debug.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13180188/app-release_debug.zip)
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/aleksey-saenko/MusicRecognizer/issues/1#issuecomment-1781473576
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
-- 
Jan Volkers
0611243237

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Akruidenberg** [comment]
Same problemen for me. Populair songs are not found.

**Comment by DocSniper** [comment]
@aleksey-saenko 
Tried the debug version, no big difference. The recording is still distorted and noisy.
I'm attaching two AAC files from the app, one recorded in a quiet room and one while music was playing: 
[aac.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13187058/aac.zip)

**Comment by aleksey-saenko** [comment]
I confirm that there is a problem with audio encoding on some devices. It will take some time to identify the cause and fix the issue. Thanks for your feedback.

**Comment by Jepzelf** [comment]
Thank you for recognizing the problem and working on it.

On October 27, 2023 11:03:48 AM GMT+02:00, Aleksey Saenko ***@***.***> wrote:
> I confirm that there is a problem with audio encoding on some devices. It will take some time to identify the cause and fix the issue. Thanks for your feedback.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/aleksey-saenko/MusicRecognizer/issues/1#issuecomment-1782560775
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>
-- 
Jan Volkers
0611243237

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aleksey-saenko** [comment]
@DocSniper 
@Jepzelf
@Akruidenberg
Could someone please check this build?
The audio recording can also be checked on the developer screen (at the bottom of the settings screen).
[app-release-debug2.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13190114/app-release-debug2.zip)

**Comment by DocSniper** [comment]
@aleksey-saenko 
Yes great, it works very well now with the app-release-debug2.zip version. See the pictures in the attachment. 
Thanks for fixing it. What was the issue ?
![Audile_DEBUG2_OK](https://github.com/aleksey-saenko/MusicRecognizer/assets/3104188/aa3b3826-9dbd-4999-bbe9-e22961945e80)

**Comment by Akruidenberg** [comment]
Tested working great now! Thanks.

**Comment by aleksey-saenko** [comment]
Cool, thanks for testing!
The updated app version will appear on F-Droid in the coming days.

**Comment by Jepzelf** [comment]
Yes! The app works great now. Even a relatively unknown track (Storm and thunder, Earth and Fire) is perfectly recognized.
Thank you for your work an for a nice app, Aleksej.
