### ISSUE TITLE
Can you please add identifiable User-Agent to requests?

### ISSUE THREAD

**Issue by AudD-music** [aleksey-saenko/MusicRecognizer#13]
Hi there,

Congrats on the app! It looks awesome!

Our systems have seen some unusual sign-ups before we identified the requests were coming from the users of this app, so we think most of the requests aren't coming through now.

Can you please identify the app in the API requests you're sending to us via the User-Agent header? That'd be helpful and would allow requests to come through.

Thank you!

**Comment by aleksey-saenko** [comment]
Hi!
Sure, the User-Agent header with syntax `app-name/app-version (platform-details)` will be added in future app releases (starting from v1.1.1).
Thanks for your attention for this app and for the great service!

**Comment by aleksey-saenko** [comment]
@AudD-music 
Version 1.1.1, including the User-Agent header, was released on F-Droid. Could you please confirm if this update helped to allow the requests to come through?

**Comment by AudD-music** [comment]
Thanks, it looks like the requests are sent correctly.
