### ISSUE TITLE
Won't open apple music links

### ISSUE THREAD

**Issue by tommylipb00t** [aleksey-saenko/MusicRecognizer#14]
Just the title tbh

**Comment by aleksey-saenko** [comment]
@tommylipb00t
Thanks for reporting. Could you please provide more info to help me understand when this occurs? What version of Android and default web browser are you using? Do you have the Apple Music app installed on your device? I assume that you see a toast "Web browser not found" after clicking, right?

**Comment by ItsEpicBeast** [comment]
I can't open spotify and youtube links even though I have the apps installed. I'm using Android 14.

**Comment by aleksey-saenko** [comment]
@tommylipb00t
@ItsEpicBeast 
Ok, I think I found the reason. Any music service link may be affected by this issue when the corresponding service app is installed on devices running Android 11 and higher.
Could you please test this build? I believe it should be working.
[audile_debug.zip](https://github.com/aleksey-saenko/MusicRecognizer/files/13276670/audile_debug.zip)

**Comment by tommylipb00t** [comment]
> @tommylipb00t Thanks for reporting. Could you please provide more info to help me understand when this occurs? What version of Android and default web browser are you using? Do you have the Apple Music app installed on your device? I assume that you see a toast "Web browser not found" after clicking, right?

I'm using android 12 (oxygen os 12), my browser is opera and I do have apple music installed. Also opening links in app is set alright
