### ISSUE TITLE
It records the sound very noisy

### ISSUE THREAD

**Issue by xmha97** [aleksey-saenko/MusicRecognizer#2]
Hi, this app records the sound very noisy.
![Screenshot_2023-10-30-23-37-00-494_com mrsep musicrecognizer](https://github.com/aleksey-saenko/MusicRecognizer/assets/23485114/bf12f65a-fb94-4ee0-b9dc-cfca15a9da28)
Please fix it.
Thanks 🙏

**Comment by aleksey-saenko** [comment]
@xmha97 
Hi there! Did you see this [thread](https://github.com/aleksey-saenko/MusicRecognizer/issues/1)?

**Comment by aleksey-saenko** [comment]
@xmha97 
The app was updated to v1.0.1 (available on F-droid). Please check the latest version and let me know how it worked on your device.

**Comment by xmha97** [comment]
This version is working on my phone, thanks. 🙏
![Screenshot_2023-11-01-18-04-34-596_com.mrsep.musicrecognizer.jpg](https://github.com/aleksey-saenko/MusicRecognizer/assets/23485114/45cb3818-3bae-4a02-8682-f8c1089dc489)
