### ISSUE TITLE
Check for update

### ISSUE THREAD

**Issue by OmarNazzal150** [aleksey-saenko/MusicRecognizer#22]
Hi. Can you please add the ability to check for update. So if there's a new update of the app. We can download and install it. This would be useful

**Comment by aleksey-saenko** [comment]
I can't find any obstacles to using the [F-Droid](https://f-droid.org) application to receive and install updates.

**Comment by OmarNazzal150** [comment]
That's okay I will just download updates from f-droid instead. Closing this now. Check my other issue #23
