### ISSUE TITLE
Improve bottom navigation bar with material 3

### ISSUE THREAD

**Issue by OmarNazzal150** [aleksey-saenko/MusicRecognizer#23]
Hi. I don't like the bottom navigation bar. So you change it to this one here ⬇️ ![SmartSelect_٢٠٢٣١١١٥_٠٠٠٧٤٢_Drive.jpg](https://github.com/aleksey-saenko/MusicRecognizer/assets/135146653/c307860b-1f73-436b-8762-61f595171bd8)

**Comment by aleksey-saenko** [comment]
Hello. I don't see the problem with the current navigation bar. Although Material3 doesn't recommend hiding labels, the number of destinations is minimal and they are intuitive and clear.
Hiding labels allows to make the interface more concise and leave useful space on the screen for more important information.

**Comment by OmarNazzal150** [comment]
Oh. Ok. I understand what you said. Okay. fine that's okay. You can just keep the current bottom navigation bar. Don't improve it. Keep the current one.

**Comment by OmarNazzal150** [comment]
Closing now
