### ISSUE TITLE
Add Music Service Link

### ISSUE THREAD

**Issue by OmarNazzal150** [aleksey-saenko/MusicRecognizer#29]
Add YouTube Music and Amazon Music.

**Comment by CharlesCanlom** [comment]
Also, add Amazon Music as well

**Comment by OmarNazzal150** [comment]
Ok

**Comment by aleksey-saenko** [comment]
Version 1.2.0, which includes support for YouTube Music and Amazon Music, was released.

**Comment by OmarNazzal150** [comment]
Thanks
