### ISSUE TITLE
Feature Requests: Start recognition by clicking the button in the Quick Setting Panel, and support Chinese songs.

### ISSUE THREAD

**Issue by CornerScarf2500** [aleksey-saenko/MusicRecognizer#30]
![Screenshot_20231124_071248_One UI Home](https://github.com/aleksey-saenko/MusicRecognizer/assets/92162334/cac64346-65e4-4b67-81db-485a0aaea573)

I want a button in quick setting panel like Shazam, but not the notification. Please add this feature.

And please add support for Chinese song

**Comment by aleksey-saenko** [comment]
Quick settings tile: duplicate, see #27.
Chinese song: Please, file a single issue per problem and provide more information. It's not entirely clear what you mean by 'support.' Are there any problems with displaying symbols, or is it a recognition issue? Regarding recognition, the app relies on the AudD service and cannot improve the output.
