### ISSUE TITLE
Copy service links

### ISSUE THREAD

**Issue by iJahangard** [aleksey-saenko/MusicRecognizer#32]
It can be useful if we were able to copy music service links directly, in current status it take us to the browser and then you have to copy it from browser addressbar, it can be done with press and hold service name

Also it will be a good feature if we can share an specific service link!

**Comment by aleksey-saenko** [comment]
Thank you for the suggestions.
A fix for the incorrect sharing format has been added to the next release (already in F-Droid build cycle). Copy on hold will be available in future releases.

**Comment by aleksey-saenko** [comment]
Added in version 1.2.0, which is available on F-Droid.
