### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mikropsoft** [aleksey-saenko/MusicRecognizer#47]
Hi, where can i get the strings.xml file of the application? can you send me instructions

**Comment by aleksey-saenko** [comment]
Hi there!
You can find strings [here](https://github.com/aleksey-saenko/MusicRecognizer/tree/master/core/strings/src/main/res). Also, if you want to make a translation, take a look at the closed pull requests for examples.

**Comment by mikropsoft** [comment]
> Hi there! You can find strings [here](https://github.com/aleksey-saenko/MusicRecognizer/tree/master/core/strings/src/main/res). Also, if you want to make a translation, take a look at the closed pull requests for examples.

Thanks you.
