### ISSUE TITLE
Android 6?

### ISSUE THREAD

**Issue by Tyomix** [aleksey-saenko/MusicRecognizer#49]
Hi! Is it possible to compile the app with Android 6 support?

**Comment by aleksey-saenko** [comment]
Hello. If I answer your question directly, then yes, it is possible. By changing just one line, you can successfully compile a build for Android 6. However, I have not tested this build in runtime.

Unfortunately, I don't see the necessity of doing this for official releases. The percentage of devices running Android 6-7 in the world is about 3-4%, and this percentage will only decrease. At the same time, this introduces potential limitations and also increases the maintenance and testing efforts over time. This time could be better spent on introducing new features.

If you really want to, you can fork the project, change the min SDK to 23, and try it out. But in general, it is advisable to refrain from using such old versions, not only for usability reasons but also for security considerations.

**Comment by Tyomix** [comment]
Thanks for your answer. I tried for several hours to build but still can't get my IntelliJ IDEA to work.
```
Execution failed for task ':core:strings:extractDebugAnnotations'.
> Could not resolve all files for configuration ':core:strings:detachedConfiguration1'.
   > Could not find lint-31.3.1.jar (com.android.tools.lint:lint:31.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint/31.3.1/lint-31.3.1.jar
   > Could not find lint-checks-31.3.1.jar (com.android.tools.lint:lint-checks:31.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/31.3.1/lint-checks-31.3.1.jar
   > Could not find lint-api-31.3.1.jar (com.android.tools.lint:lint-api:31.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-api/31.3.1/lint-api-31.3.1.jar
   > Could not find intellij-core-31.3.1.jar (com.android.tools.external.com-intellij:intellij-core:31.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/intellij-core/31.3.1/intellij-core-31.3.1.jar
   > Could not find kotlin-compiler-31.3.1.jar (com.android.tools.external.com-intellij:kotlin-compiler:31.3.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/31.3.1/kotlin-compiler-31.3.1.jar
```

Can download this files with my browser tho...
Can you make an apk for my lovely Galaxy Note 4 running Android 6, please! :)

**Comment by aleksey-saenko** [comment]
Unfortunately, the build is not working at all. The app is being compiled, but when running on the emulator, it crashes repeatedly. If we try look at the reasons, there are actually dozens of incompatible code sections. Android lint highlights them, but they don't affect the app build. To adapt all of this, a lot of code needs to be rewritten. I'm sorry, but it seems like it won't work.

**Comment by Tyomix** [comment]
That's alright, thank you for support.
