### ISSUE TITLE
Tap to recognize widget

### ISSUE THREAD

**Issue by liz-desartiges** [aleksey-saenko/MusicRecognizer#52]
I just came accross this app looking for an alternative to shazam widget.

some android flavor allow to have widget on their lockscreen (samsung for exemple), and also a widget on the home screen can be quite useful.

I also own a z flip 5 and it's possible with just a few line of xml to allow your widget to be displayed on the external screen which is my main reason to wanting an alternative to shazam.

But unfortunately I have no experience with either kotlin or android development. I will try to look into it, but I would need some help

**Comment by aleksey-saenko** [comment]
Hi. Yeah, it would be nice to have a widget.
You can certainly try to develop it yourself, and I'm ready to discuss any pull requests. But without a good knowledge of Kotlin and Android, it might be challenging to achieve good results. I've added this feature to the upcoming backlog, and when I have some time, I'll see what can be done.

**Comment by aleksey-saenko** [comment]
Added in version 1.5.0, which is available on F-Droid. You can check how it works on your device.

**Comment by liz-desartiges** [comment]
I just checked and I think one properties in the widget xml is wrong, I'm currently rebuilding it with this change
```
index 02712c7..1bfe5c2 100644
--- a/feature/recognition/src/main/res/xml/recognition_widget_info.xml
+++ b/feature/recognition/src/main/res/xml/recognition_widget_info.xml
@@ -10,4 +10,4 @@
     android:targetCellWidth="4"
     android:targetCellHeight="1"
     android:updatePeriodMillis="0"
-    android:widgetCategory="home_screen" />
\ No newline at end of file
+    android:widgetCategory="keyguard|home_screen" />
\ No newline at end of file
```

**Comment by aleksey-saenko** [comment]
When clicked, the widget launches a transparent activity to check permissions and request them if necessary, then launches the service. Most likely, opening the activity will request you to unlock the screen, which may not be the expected behavior. But it's good if you check. My devices don't allow me to add widgets to my lock screen.

**Comment by liz-desartiges** [comment]
with my change it gets listed as widget compatible with the coverscreen.
the authentification thingy is not an issue here because all those widgets ask for id anyway to be used on my phone

**Comment by aleksey-saenko** [comment]
So you have to unlock the screen to access the widget? What then is the point of such widgets?

**Comment by liz-desartiges** [comment]
I have a foldable flip phone and on it you have regular android widgets that you can run without opening your phone, which is pretty useful for things like shazam or audile

**Comment by liz-desartiges** [comment]
like so 
![image](https://github.com/aleksey-saenko/MusicRecognizer/assets/19488257/853fbd09-77e8-4ead-8b00-70e28455c151)

**Comment by aleksey-saenko** [comment]
But if you tap on widget does it request to unlock the screen? Do all widgets require unlocking or only Shazam and Audile?

**Comment by liz-desartiges** [comment]
no it doesn't you have to unlock to see the list of widgets, you swipe to the right to get to the widgets and if the phone is locked they ask you to authentificate, so there is no need for a second unlock

**Comment by aleksey-saenko** [comment]
Ok, sorry for all these questions, I just haven’t dealt with such devices yet) If you want you can create a pull request to add "keyguard".

**Comment by liz-desartiges** [comment]
Sorry didn't had the time to make a pr, been quite busy lately
