### ISSUE TITLE
Quick setting recognition

### ISSUE THREAD

**Issue by liz-desartiges** [aleksey-saenko/MusicRecognizer#53]
Add a quick settings that has the same behavior as the current notification service.
By that I mean when enabling the quick setting listen to the environment and recognize a song then the quick setting gets disabled

**Comment by aleksey-saenko** [comment]
Could you please describe the issue in more detail? It seems to me that the current quick settings tile works exactly the same as the notification service.

**Comment by liz-desartiges** [comment]
Yeah I see it as an alternative/replacement but providing the same feature in a different spot.

I think a quick setting is better suited for this use case as it provides a button instead of taking space in the notification tray

**Comment by liz-desartiges** [comment]
This is how Shazam do it for reference 
![Uploading Screenshot_20240425_174431.jpg…]()

**Comment by aleksey-saenko** [comment]
Your link is broken.
I am sorry, but comparing with Shazam, I see no differences.
[Screen_recording_comp2.webm](https://github.com/aleksey-saenko/MusicRecognizer/assets/109096599/f6e62835-d9fd-4d0b-8636-30658e87e65e)

**Comment by liz-desartiges** [comment]
I'm sorry I didn't see that we already had a quick setting, it's what I was thinking about
