### ISSUE TITLE
Widget?

### ISSUE THREAD

**Issue by okgamr** [aleksey-saenko/MusicRecognizer#57]
Ey-ya, why not something like Shazam (btw there is a material you version officially)
Imma post a screenshot of it 3 minutes later
![Screenshot_2024-05-27-22-15-22-941-edit_app.lawnchair.jpg](https://github.com/aleksey-saenko/MusicRecognizer/assets/128509556/2ed49016-f5ed-4485-a296-1d088cb1f1b7)

1 minute*

**Comment by aleksey-saenko** [comment]
Duplicate #52
There is already some [progress](https://github.com/aleksey-saenko/MusicRecognizer/assets/109096599/bdfb2c15-f85b-4db1-9394-05d989c13a42), most likely the widget will be added in the next release.

**Comment by okgamr** [comment]
Ok, good to go
