### ISSUE TITLE
Privacy information

### ISSUE THREAD

**Issue by kongreif** [aleksey-saenko/MusicRecognizer#59]
Currently, I can't find information about which personal data is being processed by audile.

Especially interesting would be, which personal data Audil shares with AudD, ACRCloud and Odesli.
Another information that would be interesting to a lot of users would probably be how the privacy of Audile compares to Shazam.

All of that information could be shared in the readme and (I assume also through the readme) on FDroid etc.

**Comment by aleksey-saenko** [comment]
Hello. Initial privacy policy have been added [here](https://github.com/aleksey-saenko/MusicRecognizer/blob/master/PRIVACY.md). Also, in the next version of the app, a corresponding button will be added on the app screen. Regarding Shazam ([privacy](https://www.shazam.com/privacy), [terms](https://www.shazam.com/terms)), AudD and ACRCloud, you can compare policies and choose the right one for you.

If you still have questions about how the app uses your data, I would be glad to answer.

**Comment by kongreif** [comment]
@aleksey-saenko Sorry I never got back to you. Thanks so much, the privacy policy really helps!
