### ISSUE TITLE
[Feature request] Recognition from file

### ISSUE THREAD

**Issue by NikMAX2077** [aleksey-saenko/MusicRecognizer#61]
It would be useful to be able to recognize music from a file, not only from device's microphone

**Comment by aleksey-saenko** [comment]
Hello. Your suggestion is valid, though I suspect it may not see frequent use in practice. It seems to me that having a song file without a name on one's phone is quite uncommon. Now, in such cases, you can simply play the audio in the background through the device's speaker and initiate the recognition. Please share more about your specific use case, maybe I don't see all usage scenarios.
Implementing this feature effectively won't be a straightforward task. Remote recognition services impose certain restrictions on the duration and size of the transmitted samples. As a result, we'd need to add a splitter (and probably a converter) for a large number of audio formats to the app. This would complicate maintenance and could significantly increase the size of the APK.
