### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by lucasmz-dev** [aleksey-saenko/MusicRecognizer#72]
Having Audile on a translation platform like [Weblate](https://hosted.weblate.org) would be nice. They provide free hosting for libre projects.

**Comment by lucasmz-dev** [comment]
@aleksey-saenko I *might* be able to help you set this up. I'd just need approval.

**Comment by lucasmz-dev** [comment]
Quickly set-up example: https://translate.codeberg.org/projects/testing-audile/

**Comment by aleksey-saenko** [comment]
I think it will be useful to go through this path myself to better understand how this platform works. I'll try to do this next week. If any help is needed, I'll write to you. Thank you for your involvement!

**Comment by aleksey-saenko** [comment]
It seems everything worked out. The project is available [here](https://hosted.weblate.org/projects/audile/).

**Comment by lucasmz-dev** [comment]
@aleksey-saenko FYI I am able to edit source strings from it. I don't think this is what you intend. If you'd like to disable it it should be under the translation tab for the component.

**Comment by aleksey-saenko** [comment]
@lucasmz-dev English is not my first language, which is why I allowed editing of the base locale. However, perhaps it's sufficient to use suggestions and comments, what do you think?

**Comment by lucasmz-dev** [comment]
That can work, though small projects usually don't get enough contribs to be able to do that, so IG it's fine?
If you act upon comments yes that works out, people can easily mistake the understanding of source strings sometimes, and which case every translator would get notified of that change and hmm... I'm not sure.

Personally I think since that's the base file, it'd be better to be restrictive about it to prevent unwanted modifications

**Comment by aleksey-saenko** [comment]
Ok, let's restrict access to the base file.
I'm closing this issue, but any suggestions are still welcome.
