### ISSUE TITLE
(Feature Request) Recognize audio from Video

### ISSUE THREAD

**Issue by DavidRLTG** [aleksey-saenko/MusicRecognizer#74]
It would be really nice if you could give a video file to the app, and it would recognise the song from inside the video.

If possible, it would also be amazing if the app would let you choose which part of the video to check.

**Comment by aleksey-saenko** [comment]
Hello, thanks for suggestion.
Your feature request is similar to #61. However, there is also a need to support all popular video codecs. This turns this tiny app into a super app, in addition to music recognition it will also be an audio-video player, audio extractor, splitter and converter.
Although I'm starting to think that it is not a big deal if the app size will be 30-40 MB per arch (ffmpeg is quite heavy), it also a huge amount of work.
This feature is added to the backlog as a potential development path, but it's not planned for the foreseeable future.
The current workaround is to play an audio-video fragment and simultaneously recognize it (for example, via the notification drawer).
