### ISSUE TITLE
Feature request: Option in library for list not tiles.

### ISSUE THREAD

**Issue by nutpantz** [aleksey-saenko/MusicRecognizer#8]
I prefer lists over tiles, maybe more info like scan date also
I expect this list to get quite large eventually.

**Comment by aleksey-saenko** [comment]
I was thinking about this. Most likely, an additional setting will be added for this in one of the future updates.

**Comment by aleksey-saenko** [comment]
Added in version 1.1.4, which is available on F-Droid.
